name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 1ce0ce30babd859d8b5fec8a9c9f7bd5
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}


# 1ce0ce30babd859d8b5fec8a9c9f7bd5
# 968220c97e8da1d047a9a480fa432e54